[package]
name = "tango-control"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
bincode = "1"
futures = "0.3"
socket2 = "0.5"
tarpc = { version = "0.34", features = ["tokio1"] }
tokio = "1"
once_cell = "1"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
